### ISSUE TITLE
Neos 7.x compatibility

### ISSUE THREAD

**Issue by paavo** [code-q-web-factory/neos-passwordprotectedcontent#2]
Currently – as per `composer.json` – this package is not compatible with Neos 7. 
Therefore we need to check / fix / update it.

**Comment by paavo** [comment]
I just added a PR https://github.com/code-q-web-factory/neos-passwordprotectedcontent/pull/3

**Comment by rolandschuetz** [comment]
Thanks! Tested, everything works. Just did a new release.
